name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew shadowJar check

      - name: Release version
        run: ./gradlew release -Prelease.customPassword=${GITHUB_TOKEN} -Prelease.customUsername=${GITHUB_ACTOR}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read current version
        id: read-version
        run: echo "version=v$(./gradlew -q cV -Prelease.quiet)" >> $GITHUB_OUTPUT
        if: github.ref == 'refs/heads/master'

      - name: Upload release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          artifacts: "application/build/libs/*-all.jar,plugins/*/build/libs/*-all.jar"
          tag: ${{ steps.read-version.outputs.version }}