name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: ./gradlew shadowJar check

      - name: Release version
        id: release
        run: ./gradlew release -Prelease.customPassword=${GITHUB_TOKEN} -Prelease.customUsername=${GITHUB_ACTOR}
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          artifacts: "application/build/libs/*-all.jar,plugins/*/build/libs/*-all.jar"
          tag: "v${{ steps.release.outputs.released-version }}"